name: 0512buhtpol

on:
  push:

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const botToken = '${{ secrets.TELEGRAM_BOT_TOKEN }}';
            const chatId = '${{ secrets.TELEGRAM_CHAT_ID }}';
            const branch = context.payload.ref.replace('refs/heads/', ''); 
            const commitMessage = context.payload.commits[0].message;
            const message = `ФИО за компьютером\n\nPush event detected on branch: ${branch}\nCommit message: ${commitMessage}`;

            const apiUrl = `https://api.telegram.org/bot${botToken}/sendMessage`; 

            try {
              const response = await fetch(apiUrl, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                  chat_id: chatId,
                  text: message,
                  parse_mode: "HTML"
                })
              });

              if (!response.ok) {
                throw new Error(`Failed to send Telegram message: ${response.status} ${response.statusText}`);
              }

              console.log('Telegram message sent successfully!');
            } catch (error) {
              console.error('Error sending Telegram message:', error);
           
            }
